<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_savePriceFilters</name>
   <tag></tag>
   <elementGuidId>961462c9-aac4-480d-b648-5dab06b7bba6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div[data-testid*=&quot;price_range&quot;]>div>div>div>button[id=&quot;filter-panel-save-button&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
