<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>priceFilterIsApplied</name>
   <tag></tag>
   <elementGuidId>b23ba2cd-1de7-43a3-ba32-a1680432853b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div[id*=&quot;price_range&quot;]>button[aria-pressed=&quot;true&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
